---
title: "Pronosticos"
author: "Mario"
date: "2023-03-30"
output: html_document
---

```{r setup, include=FALSE}
#1 Instalar paquete
install.packages('quantmod')
install.packages('prophet')
```


```{r}
# 2 Abrir Libreria
library(quantmod)
library(prophet)
library(tidyverse)
library(zoo)
library(lubridate)
library(xts)
library(ggplot2)
library(dplyr)
```

```{r}
# 3 traer datos
Bitcoin <- getSymbols("BTC-USD", from="2016-01-01", src="yahoo", auto.assign = F)[,6]
class(Bitcoin)
df1 <- fortify.zoo(Bitcoin)
df1 <-df1 %>% rename (ds = colnames(df1)[1], y = colnames(df1)[2])

Ether <- getSymbols("ETH-USD", from="2016-01-01", src="yahoo", auto.assign = F)[,6]
class(Ether)
df2 <- fortify.zoo(Ether)
df2 <-df2 %>% rename (ds = colnames(df2)[1], y = colnames(df2)[2])
```

```{r}
# 4 primeras predicciones BTC
modelo1 <- prophet(df1)
horizonte1 <- make_future_dataframe(modelo1, periods = 90)

forecast1 <- predict(modelo1, horizonte1)
tail(forecast1[c('ds','yhat','yhat_lower','yhat_upper')])
```


```{r}
# 5 Gráfico Pronosticos BTC
plot1 <- dyplot.prophet(modelo1, forecast1)
plot1
```
```{r}
plot2 <- prophet_plot_components(modelo1, forecast1)
plot2
```

```{r}
# 6 Primeras predcciones ETH
modelo2 <- prophet(df2)
horizonte2 <- make_future_dataframe(modelo2, periods = 31)
```

```{r}
forecast2 <- predict(modelo2, horizonte2)
tail(forecast2[c('ds','yhat','yhat_lower','yhat_upper')])
```
```{r}
plot3 <- dyplot.prophet(modelo2, forecast2)
plot3
```

```{r}
plot4 <- prophet_plot_components(modelo2, forecast2)
plot4
```


